jam/urls.py
from django.urls import path 
from jam import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
	path('', views.index, name='jam'),
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

repository/urls.py
from django.contrib import admin
from django.urls import path, include

from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='indexuser'),
    path('login', views.signin, name="signin"),
	path('logout', views.signout, name="signout"),
	path('registration', views.registration, name="registration"),

    #path app
    path('resources/', include('resources.urls')),
    path('dokumen/', include('dokumen.urls')),
    path('panduan/', include('panduan.urls')),
    path('bantuan/', include('bantuan.urls')),
    path('jam/', include('jam.urls')),
    path('berita/', include('berita.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('search/', include('search.urls')),
    
    #path api
    # path('api/', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
	path('buku/', views.search, name='search'),
	path('jurnal/', views.searchj, name='searchj'),
]

resources/templates/resources/buku.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load customfunction %}

{% block header %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock header %}

{% block content %}
	<div class="container-fluid">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-12">
					<div class="row">
						<div class="col-sm-2 border-right">
							<form action="{% url 'search:search' %}" method="GET">
								<div class="input-group search_box" style="width: 200px;">
									<input class="form-control" type="search" placeholder="Cari Buku" name="q" value="{{search}}">
									<button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
								</div>
							</form>
							<ul class="list-group list-group-flush">
								<li class="list-group-item"><h5><b>Kategori Buku</b></h5></li>
								<div class="border border-bottom"></div>
								{% for item in cat %}
								<li class="kategori_menu list-group-item"><a href="{% url 'kategori' id=item.id_kategori %}">{{ item.nama_kategori }}</a></li>
								{% endfor %}
							</ul>
						</div>
						<div class="col-sm-2">
							<div class="grid-item">
									<img style="width: 200px;" src="{{ buku.cover.url }}">
							</div>		
						</div>
			
						<div class="col-sm-6">
							
							<div class="product-information">
								<h4>{{ buku.jdl_buku }}</h4>
								<p><a href="{% url 'kategori' id=buku.kategori.id_kategori %}">{{ buku.kategori }} </a></p>
								<p style="margin: 0px">by <a style="font-weight:bold" href="{% url 'pengarang' id=buku.pengarang.id_pengarang %}">{{ buku.pengarang }}</a></p>
								<div class='rating'>
									{{ buku.totalrating|averagerating:buku.totalreview }}
									<a href='#getreview'><span class='totalrating'>{{ buku.totalreview|add:-1 }} Reviews</span></a>
								</div>
								<article class="text-justify" style="margin-top:10px;">
									{{ buku.deskripsi }}
								</article>

							</div>
							<div class="review" id="getreview">
								{% if messages %}
									<div class="messages">
										{% for message in messages %}
										<p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
										{% endfor %}
									</div>
								{% endif %}	
								<div class="rating-stars text-left">
									<ul id="stars">
									  <li id="azaa" class="star" data-value="1"> <i class="fa fa-star fa-fw"></i> </li>
									  <li id="azbb" class="star" data-value="2"> <i class="fa fa-star fa-fw"></i> </li>
									  <li id="azcc" class="star" data-value="3"> <i class="fa fa-star fa-fw"></i> </li>
									  <li id="azdd" class="star" data-value="4"> <i class="fa fa-star fa-fw"></i> </li>
									  <li id="azee" class="star" data-value="5"> <i class="fa fa-star fa-fw"></i> </li>
									</ul>
								</div>
									
							   	<form action="" method="POST" class="needs-validation" novalidate="">
								   {% csrf_token %}
								
									<div class="form-group">
										{{ form.review_star|as_crispy_field }}
									</div>
									<div class="form-group">
										{{ form.review_text|as_crispy_field }}
									</div>
									<br>
									
									<div class="form-group">
										<button class="btn btn-warning" type="submit" style="color: #fff">Submit </button>
									</div>
							   	</form>	
							   
							   	<br><br><br>
							   
								<h4>Ulasan</h4>
								{% for lreview in rreview %}
								<div class="card">
									<div class="card-body">
										<img src="{% static 'img/profile.png' %}"/>
										<b> {{ lreview.reviewer }} </b>
										<div class='rating'>
											{{ lreview.review_star|averagerating:1 }}
										</div>
										<div class="given_review_date">
											<span style="color:#555;"> {{ lreview.created }}</span>
										</div>
										<p style="margin-top: 10px"> {{ lreview.review_text }} </p>
									 </div>
								</div>
								<br>
								{% endfor %}
							</div>
								<div class="d-pagination">
									<ul class="pagination">
									{% if rreview.has_previous %}
										<li class="page-item">
											<a class="page-link" href="?page=1">First</a>
										</li>								
										<li class="page-item">
											<a class="page-link" href="?page={{ rreview.previous_page_number }}">Previous</a>
										</li>
									{% endif %}
									{% for ord in rreview.paginator.page_range %}
										{% if rreview.number == ord %}
											<li class="page-item active">
												<span class="page-link">{{ ord }}
													<span class="sr-only">(current)</span>
												</span>
											</li>
										{% elif ord > rreview.number|add:'-3' and ord < rreview.number|add:'3' %}
											<li class="page-item">
												<a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
											</li>
			
										{% endif %}
			
									{% endfor %}
									 {% if rreview.has_next %}
										<li class="page-item">
											<a class="page-link" href="?page={{ rreview.next_page_number }}">Next</a>
										</li>
										<li class="page-item">
											<a class="page-link" href="?page={{ rreview.paginator.num_pages }}">Last</a>
										</li>
									{% endif %}
									</ul>
								</div>		
						</div>
						<div class="col-sm-2">
							<div class="pricebox">
								<p>Harga: Rp. <span> {{ buku.harga }}</span></p>
								<button class="btn btn-warning" id="addTocart" data-buku-id="{{ buku.id_buku }}">
									<i class="fa fa-shopping-cart"></i> Keranjang
								</button>
							</div>
						</div>
					</div>	
				</div>
				
				<div class="col-sm-12">	
					<div class="titleheader">
						<h3 class="h2header text-center">Buku Lainnya</h3>
					</div>
					<div class="regulara sliderzx text-center">
						{% for item in rekombuku %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{{ item.cover.url }}"/>
							</div>
							<a href="{% url 'buku' id=item.id_buku %}">{{ item.jdl_buku|text_short }}</a>
                            <a href="{% url 'pengarang' id=item.pengarang.id_pengarang %}">{{ item.pengarang }}</a>
							<div class="rating">
								{{ item.totalrating|averagerating:item.totalreview }}
								<span class="totalrating">{{ item.totalreview|add:-1 }}</span>
							</div>
							<p>Rp. {{ item.harga }}</p>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}


{% block scripts %}
<script type="text/javascript">
	$(document).on('ready', function() {
		$(document).on('click', '.lookInsideImg,.lookInsideBg', function (e) {
			$('div.overlay').fadeIn(500);
			$('div.lookInsideDiv').fadeIn(500);
		});
	   
	   $(document).on('click', 'div.lookInsideDiv div.exitBtn', function () {
			$('div.overlay').fadeOut(500);
			$('div.lookInsideDiv').fadeOut(500);
			refCaro($('#bookDR99'));
		});
		$(document).on('click', 'div.overlay', function () {
			$('div.overlay').fadeOut(500);
			$('div.lookInsideDiv').fadeOut(500);
			refCaro($('#bookDR99'));
			return false
		});	
	});
</script>

{% endblock %}

resources/templates/resources/index.html
{% extends "base.html" %}
{% load static %}
{% load customfunction %}

{% block header %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock header %}

{% block content %}

	<div class="container-fluid">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-2 border-right">
					<ul class="list-group list-group-flush">
						<li class="list-group-item"><h5><b>Resources</b></h5></li>
						<div class="border border-bottom"></div>
						<li class="layanan_menu list-group-item"><a href="{% url 'bukus' %}">Buku</a></li>
						<li class="layanan_menu list-group-item"><a href="{% url 'journals' %}">Jurnal</a></li>
						<li class="layanan_menu list-group-item"><a href="{% url 'book_recommendations' %}">Rekomendasi</a></li>
					</ul>
					<br>
					<ul class="list-group list-group-flush">
						<li class="list-group-item"><h5><b>Layanan Lainnya</b></h5></li>
						<div class="border border-bottom"></div>
						<li class="layanan_menu list-group-item"><a href="{% url 'berita' %}">Berita</a></li>
						<li class="layanan_menu list-group-item"><a href="/panduan">panduan</a></li>
						<li class="layanan_menu list-group-item"><a href="/dokumen">Unduh Dokumen Petunjuk</a></li>
					</ul>
				</div>
				<div class="col-sm-10">
					<div class="container text-center">
						<p class="lead"><b>Untuk memenuhi kebutuhan pemustaka, kami menyediakan berbagai bahan perpustakaan digital online (e-Resources) seperti jurnal , ebook, dan karya-karya referensi online lainnya. Setiap anggota E-Repository yang telah memiliki nomor anggota yang sah, berhak memanfaatkan layanan koleksi digital online yang kami langgan (e-Resources).</b></p>
					</div>

					<br><br><br><br>

					<div class="titleheader">
						<h3 class="h2header text-center">Buku Terbaru</h3>
						<h5 class="h5link text-center"><a href="{% url 'bukus' %}">Lihat Semua</a></h5>
					</div>
					<div class="regulara sliderzx">
						{% for item in newbooks %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{{ item.cover.url }}"/>
							</div>
							<a href="{% url 'buku' id=item.id_buku %}">{{ item.jdl_buku|text_short }}</a>
							<a href="{% url 'pengarang' id=item.pengarang.id_pengarang %}">{{ item.pengarang }}</a>
							<div class="rating">
								{{ item.totalrating|averagerating:item.totalreview }}
								<span class="totalrating">{{ item.totalreview|add:-1 }}</span>
							</div>
							<p>Rp. {{ item.harga }}</p>
							<button class="btn btn-warning" id="addTocart" data-buku-id="{{ item.id_buku }}">
								<i class="fa fa-shopping-cart"></i> Keranjang
							</button>
						</div>
						{% endfor %}
					</div>
					
					
					<br><br><br><br>

					<div class="titleheader">
						<h3 class="h2header text-center">Journal Terbaru</h3>
						<h5 class="h5link text-center"><a href="{% url 'journals' %}">Lihat Semua</a></h5>
					</div>
					<div class="regulara sliderzx text-center">
						{% for j in newjournal %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{% static 'img/jurnal.png' %}"/>
							</div>
							<a href="{% url 'journal' id=j.kd_jurnal %}">{{ j.jdl_jurnal|text_short }}</a>
						</div>
						{% endfor %}
					</div>
					
					<br><br><br><br>

					<div class="titleheader">
						<h3 class="h2header text-center">Buku Rekomendasi</h3>
						<h5 class="h5link text-center"><a href="{% url 'rbooks' %}">Lihat Semua</a></h5>
					</div>
					<div class="regulara sliderzx text-center">
						{% for p in books %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{{ p.image_url }}"/>
							</div>
							<a href="{% url 'rbuku' bookid=p.book_id %}">{{ p.original_title|truncatechars:30 }}</a>
							<a>{{ p.authors|truncatechars:15 }}</a>
							<div class="rating">
								{{ p.average_rating|averagerating:1 }}
							</div>

							<p>Beri Nilai Untuk Buku Ini</p>
						
							{% if user.is_authenticated %}
							<div class='rating-block text-center' id='rating-block-{{ p.book_id }}' onmouseover="rateStart(this)"
								onclick='rateBook(this)' data-book-id="{{ p.book_id }}">
								<div class='rateYo text-center' id='rate-{{ p.book_id }}'></div>
							</div>
							{% else %}
							<div class='rating-block btn btn-warning text-center' onclick="location.href='{% url 'signin' %}'">
								<div id='button-text'>Login
									</a>
								</div>
							</div>
							{% endif %}
						</div>
						{% endfor %}
					</div>
				</div>
				<br>	
			</div>
		</div>
	</div>
<br><br>
{% endblock content %}

<script type="text/javascript">
	/* preloader */
	$(window).on('load', function () {
        if (readCookie('referer') == null) {
            $('.preloader-container').delay(700).fadeOut('slow');
            createCookie('referer', 1, 0);

        }

        if (readCookie('referer') != null) {

            $('.preloader-container').hide();
        }
    });

/* functions to create and read cookies */
    function createCookie(name, value, days) {
        if (days) {
            var date = new Date();
            date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
            var expires = "; expires=" + date.toGMTString();
        } else var expires = "";
        document.cookie = name + "=" + value + expires + "; path=/";
    }

    function readCookie(name) {
        var nameEQ = name + "=";
        var ca = document.cookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') c = c.substring(1, c.length);
            if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
        }
        return null;
    }

		
	/* 2 carousel */
	$('#carousel-2').carousel({
		interval: 6000,
		wrap: true,
		keyboard: true
	});

	$('#demo').carousel({
		interval: 5000,
		wrap: true,
		keyboard: true
	});

        
</script>


{% block scripts %}


	
	{% endblock scripts %}

resources/templates/resources/jurnal.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock header %}

{% block content %}

	<div class="container-fluid">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-2 border-right">
					<div class="container">
						<ul class="list-group list-group-flush">
							<li class="list-group-item"><h5><b>Kategori Jurnal</b></h5></li>
							<div class="border border-bottom"></div>
							{% for get_kategori in kategori %}
							<li class="kategori_menu list-group-item"><a href="{% url 'kategorij' id=get_kategori.id_kategorij %}">{{get_kategori.nama_kategori}}</a></li>
							{% endfor %}
						</ul>
					</div>
				</div>

	
				<div class="col-sm-8">
					<div class="container">
						<h4><b>{{jurnal.jdl_jurnal}}</b></h4>
						<p>
							<a href="">{{ jurnal.nama_kategori }} </a>
							<a>{{jurnal.pengarang}} / {{jurnal.terbitan}}</a>
						</p>
						<div class="dropdown-divider"></div>
						<br>
						<article class="text-justify" style="margin-top:10px;">
							<h5><b>Abstrak</b></h5>
							{{jurnal.abstract}}
						</article>
						<br>
						<h5><b>Kata Kunci:</b></h5> {{jurnal.keywords}}
						<br><br>
						<h5><b>Refrensi</b></h5>
							{{jurnal.refrensi}}	
						<br><br>
						<i class="fa fa-calendar"> {{jurnal.created}}</i>
					</div>
					<br><br>
				</div>
				<div class="col-sm-2 border-left">
					<div class="container">
						<form action="{% url 'search:searchj' %}" method="GET">
							<div class="input-group search_box" style="width: 200px;">
								<input class="form-control" type="searchj" placeholder="Cari Jurnal" name="j" value="{{searchj}}">
								<button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
							</div>
						</form>
						<div class="dropdown-divider"></div>
						<h5><b>Unduh Jurnal</b></h5>
						<div class="btn-group">
							<a href="{{jurnal.file.url}}" download="{{jurnal.file.url}}" class="btn btn-info"> Unduh Pdf </a>
						</div>
					</div>
				</div>
			</div>	
		</div>
	</div>

{% endblock content %}

resources/templates/resources/kategori.html
{% extends "base.html" %}
{% load static %}
{% load customfunction %}

{% block header %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock header %}

{% block content %}
<div class="row">
    <div class="col-sm-2 border-right">
        <div class="container">
            <form action="{% url 'search:search' %}" method="GET">
                <div class="input-group search_box" style="width: 200px;">
                    <input class="form-control" type="search" placeholder="Cari Buku" name="q" value="{{search}}">
                    <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
                </div>
            </form>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><h5><b>Kategori Buku</b></h5></li>
                <div class="border border-bottom"></div>
                {% for k in cat %}
                <li class="kategori_menu list-group-item"><a href="{% url 'kategori' id=k.id_kategori %}">{{ k.nama_kategori }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    
    <div class = 'col-sm-10'>
        {% for item in buku %}
        <div class="book-wrapper text-center">
            <div class="coverpage">
                <img src="{{ item.cover.url }}"/>
            </div>
            <a href="{% url 'buku' id=item.id_buku %}">{{ item.jdl_buku|text_short }}</a>
            <a href="{% url 'pengarang' id=item.pengarang.id_pengarang %}">{{ item.pengarang }}</a>
            <div class="rating">
                {{ item.totalrating|averagerating:item.totalreview }}
                <span class="totalrating">{{ item.totalreview|add:-1 }}</span>
            </div>
            <p> Rp. {{ item.harga }} </p>
            <button class="btn btn-warning" id="addTocart" data-buku-id="{{ item.id_buku }}">
                    <i class="fa fa-shopping-cart"></i> Keranjang
            </button>
        </div>
        {% endfor %}

        {% if buku|length > 0 %}
        <div class="d-pagination">
            <ul class="pagination">
            {% if buku.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">First</a>
                </li>								
                <li class="page-item">
                    <a class="page-link" href="?page={{ buku.previous_page_number }}">Previous</a>
                </li>
            {% endif %}
            {% for ord in buku.paginator.page_range %}
                {% if buku.number == ord %}
                    <li class="page-item active">
                        <span class="page-link">{{ ord }}
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                {% elif ord > buku.number|add:'-3' and ord < buku.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
                    </li>

                {% endif %}

            {% endfor %}
            {% if buku.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ buku.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ buku.paginator.num_pages }}">Last</a>
                </li>
            {% endif %}
            </ul>
        </div>
        {% else %}
        <h3 class="text-center mt-5">Pencarian tidak ditemukan.</h3>
        {% endif %}	
    </div>
</div>
<br><br>

{% endblock %}

resources/templates/resources/kategori_jurnal.html
{% extends "base.html" %}
{% load static %}
{% load customfunction %}

{% block header %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock header %}

{% block content %}
<div class="row">
    <div class="col-sm-2 border-right">
        <div class="container">
            <form action="{% url 'search:searchj' %}" method="GET">
                <div class="input-group search_box" style="width: 200px;">
                    <input class="form-control" type="searchj" placeholder="Cari Jurnal" name="j" value="{{searchj}}">
                    <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
                </div>
            </form>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><h5><b>Kategori Journal</b></h5></li>
                <div class="border border-bottom"></div>
                {% for get_kategori in catj %}
                <li class="kategori_menu list-group-item"><a href="{% url 'kategorij' id=get_kategori.id_kategorij %}">{{get_kategori.nama_kategori}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="col-sm-10">
        <div class="container">
            {% if journals|length > 0 %}
            <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col"></th>
                <th scope="col">Judul</th>
                <th scope="col">Abstrak</th>
                <th scope="col">Pengarang</th>
                <th scope="col"></th>
                </tr>
            </thead>
            {% endif %}	

            <tbody>

                {% for get_journal in journals %}
                    <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td><a href="{% url 'journal' id=get_journal.kd_jurnal %}">{{get_journal.jdl_jurnal}}</a></td>
                    <td>{{get_journal.abstract|abstrak_short}}...</td>
                    <td>{{get_journal.pengarang}}</td>
                    <td>
                        <a href="{{get_journal.file.url}}" download="{{get_journal.file.url}}">Pdf</a>
                    </td>
                    </tr>
                {% endfor %}

            </tbody>

            </table>
        </div>

        {% if journals|length > 0 %}
        <div class="d-pagination">
            <ul class="pagination">
            {% if journals.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">First</a>
                </li>								
                <li class="page-item">
                    <a class="page-link" href="?page={{ journals.previous_page_number }}">Previous</a>
                </li>
            {% endif %}
            {% for ord in journals.paginator.page_range %}
                {% if journals.number == ord %}
                    <li class="page-item active">
                        <span class="page-link">{{ ord }}
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                {% elif ord > journals.number|add:'-3' and ord < journals.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
                    </li>

                {% endif %}

            {% endfor %}
            {% if journals.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ journals.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ journals.paginator.num_pages }}">Last</a>
                </li>
            {% endif %}
            </ul>
        </div>
        {% else %}
        <h3 class="text-center mt-5">Pencarian tidak ditemukan.</h3>
        {% endif %}	
    </div>
</div>
<br><br>
{% endblock %}

resources/templates/resources/penulis.html
{% extends 'base.html' %}
{% load static %}
{% load customfunction %}

{% block header %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock header %}

{% block content %}
    <div class="container-fluid">
        <div class="container-fluid">
			<div class="row">
				<div class="col-sm-12">
					<div class="row">
						<div class="col-sm-3">
							<div class="view-details">
								<img src="{{ wrt.foto.url }}">
							</div>
						</div>
						
						<div class="col-sm-8">
							<div class="product-information">
								<h3>{{ wrt.nama_pengarang }}</h3>
								<article class="text-justify" style="margin-top:10px;">{{ wrt.deskripsi_pengarang }}</article>

							</div>
						</div>
					</div>	
				</div>

				<div class="col-sm-12">
                    <div class="titleheader">
						<h3 class="h2header text-center">Karya Penulis</h3>
					</div>
					<div class="regulara sliderzx text-center">
						{% for item in buku %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{{ item.cover.url }}"/>
							</div>
							<a href="{% url 'buku' id=item.id_buku %}">{{ item.jdl_buku|text_short }}</a>
                            <a href="{% url 'pengarang' id=item.pengarang.id_pengarang %}">{{ item.pengarang }}</a>
							<div class="rating">
								{{ item.totalrating|averagerating:item.totalreview }}
								<span class="totalrating">{{ item.totalreview|add:-1 }}</span>
							</div>
							<p>Rp. {{ item.harga }}</p>
							<button class="btn btn-warning" id="addTocart" data-book-id="{{ item.id_buku }}">
									<i class="fa fa-shopping-cart"></i> Keranjang
								</button>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
        </div>
    </div>
{% endblock %}